yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<!-- includes/footer.html -->
<!DOCTYPE html>
<html lang="ru">
  <footer class="border-top text-center py-3">
    <style>
      body {
        font-family: PT Astra Sans;
         background-color: white;
         }
      .footer {
        background-color: lightskyblue;
         position: fixed;
         right: 0;
         bottom: 0;
         text-align: center; 
         width: 100%;   
         font-size: 14px;
      font-weight: bold;
        color: #fafaff;
        height: 50px;
       }
      </style>
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>
</html>

yatube/templates/includes/header.html
<!-- includes/header.html -->
<!DOCTYPE html>
<html lang="ru">  
  <header>  {% load static %}
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src={% load static %} "{% static '/img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          </img>
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube</a>
          <ul class="nav nav-pills">
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}" 
               href="{% url 'posts:index' %}">Главная страница</a>
          </li>
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
                 href="{% url 'about:author' %}">Об авторе</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
                 href="{% url 'about:tech' %}">Технологии</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link  {% if view_name  == 'new_post' %}active{% endif %}" 
                 href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
                 href="{% url 'users:password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
                 href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              <p>Пользователь: {{ user.username }}</p>
            </li>
            {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
                 href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
              href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            {% endif %}
          {% endwith %}
      </div>
    </nav>      
  </header>
</html>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}