yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Адрес группы', unique=True)
    description = models.TextField('Описание группы', max_length=200)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Заполните это поле.'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост.',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Оставьте свой комментарий тут',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = (models.UniqueConstraint(
            fields=('author', 'user'),
            name='unique_follower'),
        )

    def __str__(self) -> str:
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': 'Напишите свой пост ниже',
            'group': 'Группа',
            'image': 'Картинка',
        }

    def clean(self):
        super(PostForm, self).clean()
        text = self.cleaned_data.get('text')
        if text is None or len(text) == 0:
            self._errors['text'] = self.error_class([
                'А кто поле будет заполнять? Пушкин?'
            ])
        return self.cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

    def clean(self):
        super(CommentForm, self).clean()
        text = self.cleaned_data.get('text')
        if text is None or len(text) == 0:
            self._errors['text'] = self.error_class([
                'А кто поле будет заполнять? Пушкин?'
            ])
        return self.cleaned_data

yatube/posts/views.py
"""Posts's view function."""
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def get_page_context(queryset, request):
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20, key_prefix='index_page')
def index(request):
    context = {'page_obj': get_page_context(
        Post.objects.select_related('author'),
        request)}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_page_context(group.posts.select_related('group'), request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author')
    following = (request.user.is_authenticated
                 and Follow.objects.filter(
                     user=request.user,
                     author=author).exists())
    context = {
        'following': following,
        'author': author,
        'page_obj': get_page_context(posts, request),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post.objects.select_related('author'), pk=post_id)
    n_posts = post.author.posts.count()
    comments = Comment.objects.filter(post_id=post_id)
    context = {
        'post': post,
        'n_posts': n_posts,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if request.method == "POST" and form.is_valid:
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author'),
        pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    context = {
        'page_obj': get_page_context(
            Post.objects.filter(author__following__user=request.user),
            request)
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user, author=author
    ).delete()
    return redirect("posts:profile", username=author)

yatube/templates/posts/create_post.html
<!-- Create_post page. -->
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %} <title>Новая запись</title> {% endblock %}
{% block content %} 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5"> 
      <div class="card">
        <div class="card-header"> 
          <h1>
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}  
          </h1>
        </div>
        <form method="post" enctype="multipart/form-data" action="{% if is_edit %}
        {% url 'posts:post_edit' post_id=form.instance.id %}
        {% else %} {% url 'posts:post_create' %} {% endif %}">
        {% csrf_token %}
          <div class="card-body">    
            {% for field in form %}
            {% if field.errors %}
            <div class="form-error">{{ field.errors }}</div>
            {% endif %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.text.id_for_label }}">                  
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="reqired text-danger">*</span>
                  {% endif %}
                  <div class="col-md-9">
                    {{ field|addclass:"form_control" }}
                  </div>
                  {% if field.help_text %}
                    <small id="{{ field.text.id_for_label }}-help" class="form-text text-muted"> 
                  {{ field.help_text|safe }} 
                  </small>
                  {% endif %}
                </label> 
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">              
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить изменения
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!-- Follow -->
{% extends 'base.html' %}
  {% block title %}
    <title>Мои подписки</title>
  {% endblock %}
    {% block content %}
      <div class="container py-5">     
        <h1>Мои подписки</h1>
          {% include 'posts/includes/switcher.html' with follow=True %}
          {% for post in page_obj %}
            <li>Автор: {{ post.author.get_full_name }}</li>
            <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}  
            <p>{{ post.text }}</p>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
              <hr>
            {% endif %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
      </div>
    {% endblock %}

yatube/templates/posts/group_list.html
<!-- Group page. -->
{% extends 'base.html' %}
{% load thumbnail %}
{% load%}
  {% block title %}
    <title>{{ group.title }}</title>
  {% endblock %}
  {% block content %}
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in page_obj %}
          <li>Автор: {{ post.author.get_full_name }}</li>
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
          <li>
          {% if author != post.author %}
            <a class="button fast white" href="{% url 'posts:profile' post.author %}">все_посты_пользователя</a>
          {% endif %}
          </li>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}    
            <p>{{ post.text }}</p>
            <li>
            <a class="button fast white" href="{% url 'posts:post_detail' post.pk %}">подробная_информация </a>
            </li>
            <li>
            {% if post.group and group != post.group %}
            <a class="button fast white" href="{% url 'posts:group_list' post.group.slug %}">все_записи_группы</a>
            {% endif %}
            </li>
          {% if not forloop.last %}
            <hr>
        {% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/index.html
<!-- Main page. -->
{% extends 'base.html' %}
  {% block title %}
    <title>Последние обновления на сайте</title>
  {% endblock %}
    {% block content %}
    {% include 'posts/includes/switcher.html' with index=True %}
      <div class="container py-5">     
        <h1>Главная страница</h1>
          {% for post in page_obj %}
            <li>Автор: {{ post.author.get_full_name }}</li>
            <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
            {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}  
            <p>{{ post.text }}</p>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
              <hr>
            {% endif %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
      </div>
    {% endblock %}

yatube/templates/posts/post_detail.html
<!-- Post detail page. -->
{% extends 'base.html' %}
{% block title %}
    <title>{{ post|slice:":30" }}</title>
{% endblock %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ n_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                <button type="submit" class="btn btn-primary">
                Все посты пользователя
                </button>
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% load thumbnail %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          <p>
           {{ post }}
          </p>
          {% if post.author == request.user %}
          <a href="{% url 'posts:post_edit' post.pk %}">
            <button type="submit" class="btn btn-primary">
            Редактировать запись
            </button>
          </a>
          {% endif %}
          {% load user_filters %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                  <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}      
                    <div class="form-group mb-2">
                      {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                  </form>
                 </div>
                </div>
              {% endif %}

              {% for comment in comments %}
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                      {{ comment.author.username }}
                    </a>
                  </h5>
                  <p>
                    {{ comment.text }}
                  </p>
                </div>
              </div>
              {% endfor %}
        </article>
      </div>
    {% endblock %}

yatube/templates/posts/profile.html
<!-- Profile page. -->
{% extends 'base.html' %}
  {% block title %}
    <title>Профайл пользователя {{ author.get_full_name }}</title>
  {% endblock %}
    {% block content %}
      <div class="container py-5">
        <div class="mb-5">        
          <h1>Все посты пользователя {{ author.get_full_name }} </h1>
            <h3>Всего постов:{{ author.posts.count }}</h3>
            {% if following %}
              <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
              Отписаться
              </a>
            {% else %}
              <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
              Подписаться
              </a>
            {% endif %}
        </div>  
            {% for post in page_obj %}   
              <article>
                <li>
                  Автор: {{ post.author.get_full_name }}
                  <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% load thumbnail %}
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
              </article>
              {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}
            {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>
    {% endblock %}